### ISSUE TITLE
Multithreaded tests occasionally failing on Windows

### ISSUE THREAD

**Issue by jeromekelleher** [jeromekelleher/msprime#344]
One particular test seems to fail sometimes on AppVeyor. It's probably reflecting a bad assumption somewhere in the test rather than some problem with the actual code being tested. 

The current solution is to rerun the test, but it should be fixed.

```
ERROR: test_simplify_access_nodes (tests.test_threads.TestTables)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\msprime\tests\test_threads.py", line 297, in test_simplify_access_nodes
    self.run_simplify_access_table("nodes", "time")
  File "C:\projects\msprime\tests\test_threads.py", line 279, in run_simplify_access_table
    self.run_failing_reader(writer, reader)
  File "C:\projects\msprime\tests\test_threads.py", line 231, in run_failing_reader
    failures = sum(results)
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'
```

**Comment by jeromekelleher** [comment]
Worked around this in #345 as random build failures working up to a release would be unhelpful. Still need to solve this properly though.

**Comment by jeromekelleher** [comment]
See also #502. When closing this we should check this issue carefully.
