### ISSUE TITLE
SparseTree.draw() fails when mutations are on root node

### ISSUE THREAD

**Issue by molpopgen** [jeromekelleher/msprime#377]
When using the Tables API to process data from forward simulations, it is not uncommon to end up with mutations associated with the root node of one or more trees.  When mutations are on the root, `SparseTree.draw()` raises `KeyError`.

Example:

```py
import msprime

print(msprime.__version__)
print(msprime.__file__)

n = msprime.NodeTable()
e = msprime.EdgeTable()
s = msprime.SiteTable()
m = msprime.MutationTable()

n.add_row(flags=1, time=0.0)
n.add_row(flags=1, time=0.0)
n.add_row(flags=0, time=1.0)

e.add_row(left=0, right=1, child=0, parent=2)
e.add_row(left=0, right=1, child=1, parent=2)

s.add_row(position=0.5, ancestral_state='0', metadata=None)
m.add_row(site=0, node=2, derived_state='1')

# msprime.sort_tables(nodes=n,edges=e,sites=s,mutations=m)
ts = msprime.load_tables(nodes=n, edges=e, sites=s, mutations=m)

t = next(ts.trees())
t.draw(path="test.svg")
```

Output:

```
0.4.1.dev937+gf8ed3cb
/Users/krthornt/src/msprime/msprime/__init__.py
Traceback (most recent call last):
  File "drawissue.py", line 25, in <module>
    t.draw(path="test.svg")
  File "/Users/krthornt/src/msprime/msprime/trees.py", line 534, in draw
    node_label_text=node_label_text)
  File "/Users/krthornt/src/msprime/msprime/drawing.py", line 67, in draw_tree
    node_label_text=node_label_text)
  File "/Users/krthornt/src/msprime/msprime/drawing.py", line 127, in __init__
    self._assign_coordinates()
  File "/Users/krthornt/src/msprime/msprime/drawing.py", line 158, in _assign_coordinates
    y2 = self._y_coords[parent]
KeyError: -1
```

**Comment by jeromekelleher** [comment]
Thanks @molpopgen --- I'm just about to make a pass at this code, so should be resolved in a few days.

**Comment by molpopgen** [comment]
I wrote this against msprime/master as of Jan 15.  It all falls apart on the current master, though, as it seems like you're tweaking this part of the code...

**Comment by jeromekelleher** [comment]
Thanks for reporting this @molpopgen, should be fixed now. Apologies also for the API churn on this --- I think this should be sufficiently flexible now, and the current API will be long-term stable from here.
