### ISSUE TITLE
msprime v 0.5.0 VariantGenerator not found

### ISSUE THREAD

**Issue by stschiff** [jeromekelleher/msprime#421]
Hi Jerome, I've installed msprime via pip3, and I tried this example (similar to an example in the tutorial) with msprime v 0.5.0:

    Python 3.6.4 (default, Mar  9 2018, 23:15:03)
    [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import msprime
    >>> tree_sequence = msprime.simulate(
    ...      sample_size=20, Ne=1e4, length=5e3, recombination_rate=2e-8,
    ...      mutation_rate=2e-8, random_seed=10)
    >>> for variant in tree_sequence.variants():
    ...      print(variant)
    ...
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/local/lib/python3.6/site-packages/msprime/trees.py", line 1953, in variants
        iterator = _msprime.VariantGenerator(self._ll_tree_sequence)
    AttributeError: module '_msprime' has no attribute 'VariantGenerator'

apparently something is broken. If I reinstall version 0.4.0, things work fine.

**Comment by jeromekelleher** [comment]
I suspect you're missing numpy @stschiff, which isn't a hard requirement for the pip install yet (it is for conda). Can you see if it's installed please?

```python
import numpy as np
````

The error message isn't at all helpful, we should definitely sort this out. Thanks for letting me know.

**Comment by stschiff** [comment]
Nope, it did give a clear error message on that front initially, telling me that numpy couldn’t be found. I then installed it via pip (I can run “import numpy as np” without problems). The problem I posted only occurs after numpy was installed.

**Comment by ashander** [comment]
I can't reproduce (on ubuntu)

```
 $ ipython
Python 3.6.4 | packaged by conda-forge | (default, Dec 23 2017, 16:31:06) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.2.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import msprime

In [2]: msprime.__version__
Out[2]: '0.5.0b2'

In [3]: tree_sequence = msprime.simulate(
   ...: ...      sample_size=20, Ne=1e4, length=5e3, recombination_rate=2e-8,
   ...: ...      mutation_rate=2e-8, random_seed=10)
   ...:      

In [4]: for variant in tree_sequence.variants():
   ...: ...      print(variant)
   ...:      
{'site': {'id': 0, 'position': 2432.768327416852, 'ancestral_state': '0', 'mutations': [{'id': 0, 'site': 0, 'node': 8, 'derived_state': '1', 'parent': -1, 'metadata': b''}], 'metadata': b''}, 'alleles': ('0', '1'), 'genotypes': array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=uint8), 'position': 2432.768327416852, 'index': 0}
{'site': {'id': 1, 'position': 2577.6939414924095, 'ancestral_state': '0', 'mutations': [{'id': 1, 'site': 1, 'node': 44, 'derived_state': '1', 'parent': -1, 'metadata': b''}], 'metadata': b''}, 'alleles': ('0', '1'), 'genotypes': array([1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
      dtype=uint8), 'position': 2577.6939414924095, 'index': 1}
{'site': {'id': 2, 'position': 2844.682702049562, 'ancestral_state': '0', 'mutations': [{'id': 2, 'site': 2, 'node': 27, 'derived_state': '1', 'parent': -1, 'metadata': b''}], 'metadata': b''}, 'alleles': ('0', '1'), 'genotypes': array([0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
      dtype=uint8), 'position': 2844.682702049562, 'index': 2}
{'site': {'id': 3, 'position': 4784.266628557816, 'ancestral_state': '0', 'mutations': [{'id': 3, 'site': 3, 'node': 8, 'derived_state': '1', 'parent': -1, 'metadata': b''}], 'metadata': b''}, 'alleles': ('0', '1'), 'genotypes': array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=uint8), 'position': 4784.266628557816, 'index': 3}
```

env: 

```
 $ conda list
# packages in environment at /home/jaime/miniconda3/envs/jlab:
#
bleach                    2.0.0                      py_1    conda-forge
ca-certificates           2018.1.18                     0    conda-forge
certifi                   2018.1.18                py36_0    conda-forge
decorator                 4.1.2                    py36_0    conda-forge
entrypoints               0.2.3                    py36_1    conda-forge
gmp                       6.1.2                         0    conda-forge
gsl                       2.1                           2    conda-forge
hdf5                      1.10.1                        2    conda-forge
html5lib                  1.0.1                      py_0    conda-forge
intel-openmp              2018.0.0             hc7b2577_8  
ipykernel                 4.8.2                    py36_0    conda-forge
ipython                   6.2.1                    py36_1    conda-forge
ipython_genutils          0.2.0                    py36_0    conda-forge
jedi                      0.11.1                   py36_0    conda-forge
jinja2                    2.10                     py36_0    conda-forge
jsonschema                2.6.0                    py36_1    conda-forge
jupyter_client            5.2.2                    py36_0    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
jupyterlab                0.31.8                   py36_1    conda-forge
jupyterlab_launcher       0.10.5                   py36_0    conda-forge
libgcc-ng                 7.2.0                h7cc24e2_2  
libgfortran               3.0.0                         1  
libgfortran-ng            7.2.0                h9f7466a_2  
libsodium                 1.0.15                        1    conda-forge
markupsafe                1.0                      py36_0    conda-forge
mistune                   0.8.3                      py_0    conda-forge
mkl                       2018.0.1             h19d6760_4  
msprime                   0.5.0b2                  py36_2    conda-forge
nbconvert                 5.3.1                      py_1    conda-forge
nbformat                  4.4.0                    py36_0    conda-forge
ncurses                   5.9                          10    conda-forge
notebook                  5.4.0                    py36_0    conda-forge
numpy                     1.14.1           py36h3dfced4_1  
openblas                  0.2.20                        7    conda-forge
openssl                   1.0.2n                        0    conda-forge
pandoc                    2.1.1                         0    conda-forge
pandocfilters             1.4.1                    py36_0    conda-forge
parso                     0.1.1                      py_0    conda-forge
pexpect                   4.4.0                    py36_0    conda-forge
pickleshare               0.7.4                    py36_0    conda-forge
pip                       9.0.1                    py36_1    conda-forge
prompt_toolkit            1.0.15                   py36_0    conda-forge
ptyprocess                0.5.2                    py36_0    conda-forge
pygments                  2.2.0                    py36_0    conda-forge
pyparsing                 2.2.0                    py36_0    conda-forge
python                    3.6.4                         0    conda-forge
python-dateutil           2.6.1                    py36_0    conda-forge
pyzmq                     17.0.0                   py36_3    conda-forge
readline                  7.0                           0    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                38.5.1                   py36_0    conda-forge
simplegeneric             0.8.1                    py36_0    conda-forge
six                       1.11.0                   py36_1    conda-forge
sqlite                    3.20.1                        2    conda-forge
svgwrite                  1.1.12                     py_0    conda-forge
terminado                 0.8.1                    py36_0    conda-forge
testpath                  0.3.1                    py36_0    conda-forge
tk                        8.6.7                         0    conda-forge
tornado                   4.5.3                    py36_0    conda-forge
traitlets                 4.3.2                    py36_0    conda-forge
wcwidth                   0.1.7                    py36_0    conda-forge
webencodings              0.5                      py36_0    conda-forge
wheel                     0.30.0                   py36_2    conda-forge
xz                        5.2.3                         0    conda-forge
zeromq                    4.2.3                         2    conda-forge
zlib                      1.2.11                        0    conda-forge
```

**Comment by jeromekelleher** [comment]
> Nope, it did give a clear error message on that front initially, telling me that numpy couldn’t be found. I then installed it via pip (I can run "import numpy as np" without problems). The problem I posted only occurs after numpy was installed.

Ah, OK, I think I know what has happened. Numpy needs to be installed when you're installing msprime as it's a compile-time dependency. If the numpy headers can't be found, the parts of msprime that depend on the numpy C API won't be built. This was done because numpy used to be quite an awkward dependency, and I wanted users of mspms to be able to use it without installing numpy. Within binary wheels now though, I think we should make numpy a hard requirement and avoid all this.

Can you try reinstalling msprime, ensuring that numpy is installed first?

**Comment by stschiff** [comment]
Ah OK. Now it works. I reinstalled it using 

    pip3 install --force-reinstall --ignore-installed --no-binary :all: msprime==0.5.0

and it now works. Thanks!

**Comment by jeromekelleher** [comment]
Excellent!
