### ISSUE TITLE
More than 256 demes triggers error

### ISSUE THREAD

**Issue by petrelharp** [jeromekelleher/msprime#61]
... at least, when running with `mspms (...) -f`.

To reproduce:

    mspms 8 2 -T -f spatial_grid_256.ms.txt

Output:

```
Traceback (most recent call last):
  File "/usr/local/bin/mspms", line 11, in <module>
    load_entry_point('msprime==0.4.1.dev5+ngf7f9a5f.d20161017', 'console_scripts', 'mspms')()
  File "/usr/local/lib/python3.5/dist-packages/msprime/cli.py", line 743, in mspms_main
    sr.run(sys.stdout)
  File "/usr/local/lib/python3.5/dist-packages/msprime/cli.py", line 192, in run
    self._simulator.run()
  File "/usr/local/lib/python3.5/dist-packages/msprime/trees.py", line 1169, in run
    self._ll_sim = self.create_ll_instance()
  File "/usr/local/lib/python3.5/dist-packages/msprime/trees.py", line 1159, in create_ll_instance
    coalescence_record_block_size=self._coalescence_record_block_size)
_msprime.InputError: Bad parameter value provided
```

This does not happen with a 15 x 16 grid; only at 16 x 16 and above.
[spatial_grid_256.ms.txt](https://github.com/jeromekelleher/msprime/files/536920/spatial_grid_256.ms.txt)

**Comment by jeromekelleher** [comment]
Ah. Population IDs are 8 bit numbers right now. There's no deep reason for this, I just didn't imagine simulating on large numbers of populations. I take it that this is something you're interested in? It's an easy enough fix (which I'm happy to do), just requires a little bit of care.

**Comment by petrelharp** [comment]
Yes, I am already using `ms` with more than 256 populations!
